/**
 * Solana Rate Limiter CLI Client
 * 
 * Demonstrates on-chain rate limiting as a Web2 backend pattern.
 * 
 * Usage:
 *   npx ts-node client/index.ts init
 *   npx ts-node client/index.ts create-key --tier 0
 *   npx ts-node client/index.ts check         (simulate a request)
 *   npx ts-node client/index.ts spam          (hit rate limit)
 *   npx ts-node client/index.ts status
 */

import * as anchor from "@coral-xyz/anchor";
import { PublicKey, Keypair, Connection, clusterApiUrl } from "@solana/web3.js";
import * as fs from "fs";
import * as path from "path";

// Program ID (update after deployment)
const PROGRAM_ID = new PublicKey("RateLm1tXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
const WINDOW_SIZE = 3600; // 1 hour in seconds
const TIER_NAMES = ["Free (10 req/hr)", "Basic (100 req/hr)", "Pro (1000 req/hr)"];

function loadOrCreateKeypair(filePath: string): Keypair {
  if (fs.existsSync(filePath)) {
    const secretKey = Uint8Array.from(JSON.parse(fs.readFileSync(filePath, "utf8")));
    return Keypair.fromSecretKey(secretKey);
  }
  const kp = Keypair.generate();
  fs.writeFileSync(filePath, JSON.stringify(Array.from(kp.secretKey)));
  console.log(`Created new keypair at ${filePath}`);
  return kp;
}

async function main() {
  const command = process.argv[2] || "status";
  
  // Setup connection (devnet)
  const connection = new Connection(clusterApiUrl("devnet"), "confirmed");
  
  // Load or create user keypair
  const keypairPath = path.join(__dirname, "user-keypair.json");
  const userKp = loadOrCreateKeypair(keypairPath);
  console.log(`User address: ${userKp.publicKey.toString()}`);
  
  // Check balance
  const balance = await connection.getBalance(userKp.publicKey);
  console.log(`Balance: ${balance / 1e9} SOL`);
  
  if (balance < 0.1e9) {
    console.log("Low balance! Run: solana airdrop 1 " + userKp.publicKey.toString() + " --url devnet");
    if (command !== "status") return;
  }
  
  // Setup Anchor provider
  const wallet = new anchor.Wallet(userKp);
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });
  
  // Load IDL (generated by anchor build)
  const idlPath = path.join(__dirname, "../target/idl/rate_limiter.json");
  if (!fs.existsSync(idlPath)) {
    console.error("IDL not found. Run: anchor build");
    return;
  }
  const idl = JSON.parse(fs.readFileSync(idlPath, "utf8"));
  const program = new anchor.Program(idl, PROGRAM_ID, provider);
  
  // Derive PDAs
  const [registryPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("registry")],
    PROGRAM_ID
  );
  const [apiKeyPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("apikey"), userKp.publicKey.toBuffer()],
    PROGRAM_ID
  );
  
  const currentWindowId = BigInt(Math.floor(Date.now() / 1000 / WINDOW_SIZE));
  const windowBytes = Buffer.alloc(8);
  windowBytes.writeBigInt64LE(currentWindowId);
  const [rateLimitStatePda] = PublicKey.findProgramAddressSync(
    [Buffer.from("ratelimit"), apiKeyPda.toBuffer(), windowBytes],
    PROGRAM_ID
  );
  
  switch (command) {
    case "init": {
      console.log("\nInitializing registry...");
      try {
        const tx = await (program.methods as any)
          .initializeRegistry()
          .accounts({
            registry: registryPda,
            authority: userKp.publicKey,
            systemProgram: anchor.web3.SystemProgram.programId,
          })
          .rpc();
        console.log(`Registry initialized! TX: https://explorer.solana.com/tx/${tx}?cluster=devnet`);
      } catch (e: any) {
        console.log("Registry may already exist:", e.message.substring(0, 100));
      }
      break;
    }
    
    case "create-key": {
      const tierArg = process.argv[4];
      const tier = parseInt(tierArg || "0");
      console.log(`\nCreating API key with tier ${tier} (${TIER_NAMES[tier]})...`);
      try {
        const tx = await (program.methods as any)
          .createApiKey(tier)
          .accounts({
            apiKey: apiKeyPda,
            registry: registryPda,
            owner: userKp.publicKey,
            systemProgram: anchor.web3.SystemProgram.programId,
          })
          .rpc();
        console.log(`API Key created! TX: https://explorer.solana.com/tx/${tx}?cluster=devnet`);
        console.log(`API Key PDA: ${apiKeyPda.toString()}`);
      } catch (e: any) {
        console.log("Error:", e.message.substring(0, 200));
      }
      break;
    }
    
    case "check": {
      console.log("\nSimulating a rate-limited request...");
      try {
        const tx = await (program.methods as any)
          .checkAndIncrement()
          .accounts({
            apiKey: apiKeyPda,
            rateLimitState: rateLimitStatePda,
            owner: userKp.publicKey,
            systemProgram: anchor.web3.SystemProgram.programId,
          })
          .rpc();
        console.log(`Request ALLOWED! TX: https://explorer.solana.com/tx/${tx}?cluster=devnet`);
        
        const state = await (program.account as any).rateLimitState.fetch(rateLimitStatePda);
        const key = await (program.account as any).apiKey.fetch(apiKeyPda);
        const limit = [10, 100, 1000][key.tier];
        console.log(`Counter: ${state.requestCount}/${limit} (${TIER_NAMES[key.tier]})`);
      } catch (e: any) {
        if (e.message.includes("RateLimitExceeded")) {
          console.log("Request DENIED: Rate limit exceeded!");
        } else if (e.message.includes("ApiKeyInactive")) {
          console.log("Request DENIED: API key is inactive.");
        } else {
          console.log("Error:", e.message.substring(0, 200));
        }
      }
      break;
    }
    
    case "spam": {
      console.log("\nSpamming requests to trigger rate limit...");
      let allowed = 0;
      let denied = 0;
      for (let i = 0; i < 15; i++) {
        try {
          await (program.methods as any)
            .checkAndIncrement()
            .accounts({
              apiKey: apiKeyPda,
              rateLimitState: rateLimitStatePda,
              owner: userKp.publicKey,
              systemProgram: anchor.web3.SystemProgram.programId,
            })
            .rpc();
          allowed++;
          process.stdout.write(".");
        } catch (e: any) {
          if (e.message.includes("RateLimitExceeded")) {
            denied++;
            process.stdout.write("X");
          } else {
            console.error("Unexpected error:", e.message.substring(0, 100));
          }
        }
      }
      console.log(`\nAllowed: ${allowed}, Denied: ${denied}`);
      break;
    }
    
    case "status": {
      console.log("\nChecking on-chain status...");
      
      // Check registry
      try {
        const registry = await (program.account as any).registry.fetch(registryPda);
        console.log(`Registry: ${totalKeys} total API keys registered`);
      } catch {
        console.log("Registry: not initialized");
      }
      
      // Check API key
      try {
        const key = await (program.account as any).apiKey.fetch(apiKeyPda);
        console.log(`\nYour API Key:`);
        console.log(`  PDA: ${apiKeyPda.toString()}`);
        console.log(`  Tier: ${key.tier} (${TIER_NAMES[key.tier]})`);
        console.log(`  Active: ${key.isActive}`);
        console.log(`  Lifetime requests: ${key.totalRequests}`);
        console.log(`  Lifetime denied: ${key.totalDenied}`);
        
        // Check current window
        try {
          const state = await (program.account as any).rateLimitState.fetch(rateLimitStatePda);
          const limit = [10, 100, 1000][key.tier];
          console.log(`\nCurrent Window:`);
          console.log(`  Requests: ${state.requestCount}/${limit}`);
          console.log(`  Window started: ${new Date(state.windowStart * 1000).toISOString()}`);
        } catch {
          console.log("\nCurrent Window: no requests yet");
        }
      } catch {
        console.log("API Key: not created yet. Run: npx ts-node client/index.ts create-key");
      }
      break;
    }
    
    default:
      console.log("Unknown command:", command);
      console.log("Available commands: init, create-key, check, spam, status");
  }
}

main().catch(console.error);
